/*
 * mirakc Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0-dev.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChannelType {
    #[serde(rename = "GR")]
    Gr,
    #[serde(rename = "BS")]
    Bs,
    #[serde(rename = "CS")]
    Cs,
    #[serde(rename = "SKY")]
    Sky,
    #[serde(rename = "BS4K")]
    Bs4K,

}

impl std::fmt::Display for ChannelType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Gr => write!(f, "GR"),
            Self::Bs => write!(f, "BS"),
            Self::Cs => write!(f, "CS"),
            Self::Sky => write!(f, "SKY"),
            Self::Bs4K => write!(f, "BS4K"),
        }
    }
}

impl Default for ChannelType {
    fn default() -> ChannelType {
        Self::Gr
    }
}

