/*
 * mirakc Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-dev.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MirakurunProgramRelatedItemsInner {
    #[serde(rename = "eventId")]
    pub event_id: i32,
    #[serde(rename = "networkId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub network_id: Option<Option<i32>>,
    #[serde(rename = "serviceId")]
    pub service_id: i32,
    #[serde(rename = "type")]
    pub r#type: String,
}

impl MirakurunProgramRelatedItemsInner {
    pub fn new(event_id: i32, service_id: i32, r#type: String) -> MirakurunProgramRelatedItemsInner {
        MirakurunProgramRelatedItemsInner {
            event_id,
            network_id: None,
            service_id,
            r#type,
        }
    }
}

