/*
 * mirakc Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0-dev.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MirakurunTunerUsersInner {
    /// User-Agent string.
    #[serde(rename = "agent", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub agent: Option<Option<String>>,
    /// User ID.
    #[serde(rename = "id")]
    pub id: String,
    /// Priority.
    #[serde(rename = "priority")]
    pub priority: i32,
}

impl MirakurunTunerUsersInner {
    pub fn new(id: String, priority: i32) -> MirakurunTunerUsersInner {
        MirakurunTunerUsersInner {
            agent: None,
            id,
            priority,
        }
    }
}

