/*
 * mirakc Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0-dev.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MirakurunProgramSeries {
    #[serde(rename = "episode")]
    pub episode: i32,
    #[serde(rename = "expireAt")]
    pub expire_at: i64,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "lastEpisode")]
    pub last_episode: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "pattern")]
    pub pattern: i32,
    #[serde(rename = "repeat")]
    pub repeat: i32,
}

impl MirakurunProgramSeries {
    pub fn new(
        episode: i32,
        expire_at: i64,
        id: i32,
        last_episode: i32,
        name: String,
        pattern: i32,
        repeat: i32,
    ) -> MirakurunProgramSeries {
        MirakurunProgramSeries {
            episode,
            expire_at,
            id,
            last_episode,
            name,
            pattern,
            repeat,
        }
    }
}
