/*
 * mirakc Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0-dev.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MirakurunChannel {
    #[serde(rename = "channel")]
    pub channel: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "services")]
    pub services: Vec<models::MirakurunChannelServicesInner>,
    #[serde(rename = "type")]
    pub r#type: models::ChannelType,
}

impl MirakurunChannel {
    pub fn new(
        channel: String,
        name: String,
        services: Vec<models::MirakurunChannelServicesInner>,
        r#type: models::ChannelType,
    ) -> MirakurunChannel {
        MirakurunChannel {
            channel,
            name,
            services,
            r#type,
        }
    }
}
