/*
 * mirakc Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0-dev.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordingFailedReasonOneOf1 {
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "osError", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub os_error: Option<Option<i32>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl RecordingFailedReasonOneOf1 {
    pub fn new(message: String, r#type: Type) -> RecordingFailedReasonOneOf1 {
        RecordingFailedReasonOneOf1 {
            message,
            os_error: None,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "io-error")]
    IoError,
}

impl Default for Type {
    fn default() -> Type {
        Self::IoError
    }
}

