/*
 * mirakc Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0-dev.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordingFailedReasonOneOf2 {
    #[serde(rename = "exitCode")]
    pub exit_code: i32,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl RecordingFailedReasonOneOf2 {
    pub fn new(exit_code: i32, r#type: Type) -> RecordingFailedReasonOneOf2 {
        RecordingFailedReasonOneOf2 {
            exit_code,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "pipeline-error")]
    PipelineError,
}

impl Default for Type {
    fn default() -> Type {
        Self::PipelineError
    }
}

