/*
 * mirakc Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-dev.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordingFailedReasonOneOf3 {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl RecordingFailedReasonOneOf3 {
    pub fn new(r#type: Type) -> RecordingFailedReasonOneOf3 {
        RecordingFailedReasonOneOf3 {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "need-rescheduling")]
    NeedRescheduling,
}

impl Default for Type {
    fn default() -> Type {
        Self::NeedRescheduling
    }
}

