/*
 * mirakc Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0-dev.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RecordingFailedReason {
    RecordingFailedReasonOneOf(Box<models::RecordingFailedReasonOneOf>),
    RecordingFailedReasonOneOf1(Box<models::RecordingFailedReasonOneOf1>),
    RecordingFailedReasonOneOf2(Box<models::RecordingFailedReasonOneOf2>),
    RecordingFailedReasonOneOf3(Box<models::RecordingFailedReasonOneOf3>),
    RecordingFailedReasonOneOf4(Box<models::RecordingFailedReasonOneOf4>),
    RecordingFailedReasonOneOf5(Box<models::RecordingFailedReasonOneOf5>),
}

impl Default for RecordingFailedReason {
    fn default() -> Self {
        Self::RecordingFailedReasonOneOf(Default::default())
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "start-recording-failed")]
    StartRecordingFailed,
    #[serde(rename = "io-error")]
    IoError,
    #[serde(rename = "pipeline-error")]
    PipelineError,
    #[serde(rename = "need-rescheduling")]
    NeedRescheduling,
    #[serde(rename = "schedule-expired")]
    ScheduleExpired,
    #[serde(rename = "removed-from-epg")]
    RemovedFromEpg,
}

impl Default for Type {
    fn default() -> Type {
        Self::StartRecordingFailed
    }
}
