/*
 * mirakc Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0-dev.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RecordingFailedReasonOneOf5 {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl RecordingFailedReasonOneOf5 {
    pub fn new(r#type: Type) -> RecordingFailedReasonOneOf5 {
        RecordingFailedReasonOneOf5 { r#type }
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "removed-from-epg")]
    RemovedFromEpg,
}

impl Default for Type {
    fn default() -> Type {
        Self::RemovedFromEpg
    }
}
