/*
 * mirakc Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0-dev.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebRecordingScheduleInput : Input data used when creating a recording schedule.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebRecordingScheduleInput {
    /// Recording options.
    #[serde(rename = "options")]
    pub options: Box<models::RecordingOptions>,
    /// A Mirakurun program ID of the target TV program.
    #[serde(rename = "programId")]
    pub program_id: i64,
    /// A list of tags.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl WebRecordingScheduleInput {
    /// Input data used when creating a recording schedule.
    pub fn new(options: models::RecordingOptions, program_id: i64) -> WebRecordingScheduleInput {
        WebRecordingScheduleInput {
            options: Box::new(options),
            program_id,
            tags: None,
        }
    }
}

