/*
 * mirakc Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0-dev.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebRecordingStatus : A recording status.
/// A recording status.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WebRecordingStatus {
    #[serde(rename = "recording")]
    Recording,
    #[serde(rename = "finished")]
    Finished,
    #[serde(rename = "canceled")]
    Canceled,
    #[serde(rename = "failed")]
    Failed,

}

impl std::fmt::Display for WebRecordingStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Recording => write!(f, "recording"),
            Self::Finished => write!(f, "finished"),
            Self::Canceled => write!(f, "canceled"),
            Self::Failed => write!(f, "failed"),
        }
    }
}

impl Default for WebRecordingStatus {
    fn default() -> WebRecordingStatus {
        Self::Recording
    }
}

