/*
 * mirakc Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0-dev.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebProcessModel : A process model constituting a pipeline.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebProcessModel {
    /// A command currently running in the pipeline.
    #[serde(rename = "command")]
    pub command: String,
    /// The process ID of a process running the command.
    #[serde(rename = "pid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pid: Option<Option<i32>>,
}

impl WebProcessModel {
    /// A process model constituting a pipeline.
    pub fn new(command: String) -> WebProcessModel {
        WebProcessModel {
            command,
            pid: None,
        }
    }
}

