/*
 * mirakc Web API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0-dev.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebRecordingRecorder : A recorder model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebRecordingRecorder {
    /// A list of process models constituting the recording pipeline.
    #[serde(rename = "pipeline")]
    pub pipeline: Vec<models::WebProcessModel>,
    /// A Mirakurun program ID of the TV program currently being recorded.
    #[serde(rename = "programId")]
    pub program_id: i64,
    /// A time when the recording started.  It's may not be equal to the start time of the TV program.
    #[serde(rename = "startedAt")]
    pub started_at: i64,
}

impl WebRecordingRecorder {
    /// A recorder model.
    pub fn new(pipeline: Vec<models::WebProcessModel>, program_id: i64, started_at: i64) -> WebRecordingRecorder {
        WebRecordingRecorder {
            pipeline,
            program_id,
            started_at,
        }
    }
}

