[workspace]

resolver = "2"
members = [ "server/kurec", "server/kurec-adapter", "server/kurec-dav-test", "server/kurec-interface", "server/mirakc-client"]

[workspace.package]
version = "0.0.1"
authors = ["KuRec Team"]
description = "KuRec - Simple, Easy, Secure and Safety Recording System"
documentation = "https://kurec-tool.github.io"
edition = "2021"
