services:
  tuner:
    build:
      context: ./mirakc-docker
    init: true
    restart: unless-stopped
    devices:
      - /dev/bus/usb
      - /dev/px4video0
      - /dev/px4video1
      - /dev/px4video2
      - /dev/px4video3
    ports:
      - 40772:40772
    volumes:
      - mirakc-config:/etc/mirakc
      - mirakc-epg:/var/lib/mirakc/epg
      - ./recorded:/recorded
      - /var/run/pcscd:/var/run/pcscd
    environment:
      TZ: Asia/Tokyo
      RUST_LOG: info
  samba:
    image: ghcr.io/servercontainers/samba
    volumes:
      - ./recorded:/recorded
    network_mode: host
    environment:
      AVAHI_NAME: tv-dev-container
      SAMBA_VOLUME_CONFIG_guest: |
        [Videos]
        path = /recorded
        read only = yes
        guest ok = yes
        browseable = yes
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

volumes:
  mirakc-config:
    name: mirakc_config
    driver: local
  mirakc-epg:
    name: mirakc_epg
    driver: local
